### ISSUE TITLE
any cross-origin extension for chrome to work Phomeme?

### ISSUE THREAD

**Issue by Gonzaluigi** [MysteryPancake/Phomeme#4]
It says in the title. I'm new on GitHub, by the way.

Phomeme didn't work without a cross-origin extension.

**Comment by MysteryPancake** [comment]
The cross-origin error is an issue from the older version which I'm working on replacing. I might make this repository private for now because it has many issues like this which are difficult to fix. Once it is finished, I will make it public again.
